name: Submodule Updates
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Submodule Update
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'stevenpall/submodule-demo'
      CHECKOUT_BRANCH: 'main'
      PR_AGAINST_BRANCH: 'main'
      OWNER: 'stevenpall'
      LABEL: 'Submodule Update'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Action
        id: run_action
        uses: releasehub-com/github-action-create-pr-parent-submodule@v1
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          parent_repository: ${{ env.PARENT_REPOSITORY }}
          checkout_branch: ${{ env.CHECKOUT_BRANCH}}
          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
          owner: ${{ env.OWNER }}
          label: ${{ env.LABEL }}
